import { useQuery } from "@tanstack/react-query";
import { Banknote, CalendarDays, Download, FileText, Loader2, ShieldCheck } from "lucide-react";
import { Layout } from "@/app/layout/Layout";
import { Button } from "@/app/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/card";
import { payrollApi } from "@/lib/api";
import { toast } from "sonner";

const money = (value: number) => new Intl.NumberFormat("en-RW", { style: "currency", currency: "RWF", maximumFractionDigits: 0 }).format(Number(value) || 0);
const monthLabel = (period: { month?: number; monthName?: string; year?: number }) => `${period.monthName || (period.month ? new Date(2000, period.month - 1).toLocaleString("en", { month: "long" }) : "Pay period")} ${period.year || ""}`.trim();

export default function MyPayslipsPage() {
  const query = useQuery({ queryKey: ["payroll", "self-service"], queryFn: payrollApi.getMyPayroll, staleTime: 30_000 });
  const download = async (id: string, employeeId: string) => {
    try {
      const { data: slip } = await payrollApi.getPayslip(id);
      const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
      const rows = (values: Array<[string, number | undefined]>) => values.filter(([, amount]) => Number(amount) > 0).map(([label, amount]) => `<div class="row"><span>${esc(label)}</span><b>${money(Number(amount))}</b></div>`).join("");
      const html = `<!doctype html><meta charset="utf-8"><title>Kubika payslip</title><style>body{font:15px Arial;max-width:720px;margin:40px auto;color:#172033}h1{margin-bottom:4px}.muted{color:#64748b}.row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #dbe2ea}.total{font-size:20px;font-weight:bold;margin-top:20px}@media print{body{margin:0 auto}}</style><h1>Payslip</h1><p class="muted">${esc(slip.employee.firstName)} ${esc(slip.employee.lastName)} · ${esc(slip.employee.employeeId)}</p><p>${esc(slip.period.monthName)} ${esc(slip.period.year)}</p><h2>Earnings</h2>${rows([["Basic salary", slip.earnings.basicSalary], ["Transport allowance", slip.earnings.transportAllowance], ["Housing allowance", slip.earnings.housingAllowance], ["Other allowances", slip.earnings.otherAllowances], ["Overtime", slip.earnings.overtime], ["Bonus", slip.earnings.bonuses], ["Commission", slip.earnings.commissions], ["Benefits in kind", slip.earnings.benefitsInKind]])}<div class="row"><b>Gross pay</b><b>${money(slip.earnings.grossSalary)}</b></div><h2>Deductions</h2>${rows([["PAYE", slip.deductions.paye], ["RSSB pension", slip.deductions.rssbPension], ["RSSB maternity", slip.deductions.rssbMaternity], ["Health insurance", slip.deductions.healthInsurance], ["Loan deductions", slip.deductions.loanDeductions], ["Other deductions", slip.deductions.otherDeductions]])}<div class="row"><b>Total deductions</b><b>${money(slip.deductions.totalDeductions)}</b></div><p class="total">Net pay: ${money(slip.netPay)}</p><script>window.onload=()=>window.print()</script>`;
      const url = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" }));
      const anchor = document.createElement("a"); anchor.href = url; anchor.download = `payslip-${employeeId}-${slip.period.year}-${String(slip.period.month).padStart(2, "0")}.html`; anchor.click(); URL.revokeObjectURL(url);
    } catch (error) { toast.error((error as Error)?.message || "Could not download payslip"); }
  };

  return <Layout><main className="mx-auto w-full max-w-6xl space-y-5 p-3 sm:p-5 lg:p-8">
    <header><p className="text-xs font-semibold uppercase tracking-widest text-cyan-600">Employee self-service</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">My payroll</h1><p className="mt-1 text-sm text-muted-foreground">Your personal payroll details and finalized payslips.</p></header>
    {query.isLoading && <div className="flex min-h-40 items-center justify-center gap-2 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin"/>Loading your payroll…</div>}
    {query.isError && <Card><CardContent className="p-5 text-sm text-rose-600">{(query.error as Error)?.message || "Could not load your payroll profile."}</CardContent></Card>}
    {query.data?.data && <>
      <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-lg"><ShieldCheck className="h-5 w-5 text-emerald-500"/>Personal details</CardTitle></CardHeader><CardContent className="grid grid-cols-1 gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">
        {[["Employee", `${query.data.data.employee.firstName} ${query.data.data.employee.lastName}`], ["Employee ID", query.data.data.employee.employeeId], ["Email", query.data.data.employee.email], ["Department", query.data.data.employee.department], ["Position", query.data.data.employee.position], ["Employment type", query.data.data.employee.employmentType], ["Tax status", query.data.data.employee.taxStatus], ["Bank", query.data.data.employee.bankName], ["Bank account", query.data.data.employee.bankAccountMasked], ["National ID", query.data.data.employee.nationalIdMasked], ["TIN", query.data.data.employee.tinMasked], ["RSSB registration", query.data.data.employee.rssbRegistrationMasked]].filter(([, value]) => value).map(([label, value]) => <div key={label as string} className="min-w-0 rounded-lg bg-muted/50 p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 break-words font-medium">{value}</div></div>)}
      </CardContent></Card>
      <Card><CardHeader className="pb-3"><CardTitle className="text-lg">Current pay details</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-lg bg-muted/50 p-3"><span className="text-xs text-muted-foreground">Basic salary</span><b className="mt-1 block">{money(Number(query.data.data.employee.currentPay.basicSalary))}</b></div><div className="rounded-lg bg-muted/50 p-3"><span className="text-xs text-muted-foreground">Transport</span><b className="mt-1 block">{money(Number(query.data.data.employee.currentPay.transportAllowance))}</b></div><div className="rounded-lg bg-muted/50 p-3"><span className="text-xs text-muted-foreground">Housing</span><b className="mt-1 block">{money(Number(query.data.data.employee.currentPay.housingAllowance))}</b></div><div className="rounded-lg bg-muted/50 p-3"><span className="text-xs text-muted-foreground">Other allowances</span><b className="mt-1 block">{money(Number(query.data.data.employee.currentPay.otherAllowances))}</b></div></CardContent></Card>
      <div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Payslips</h2><span className="text-sm text-muted-foreground">{query.data.data.count} available</span></div>
      {!query.data.data.payslips.length && <Card><CardContent className="flex flex-col items-center p-8 text-center"><FileText className="mb-3 h-8 w-8 text-muted-foreground"/><p className="font-medium">No finalized payslips yet</p><p className="mt-1 text-sm text-muted-foreground">Your payslips will appear here after payroll is finalized.</p></CardContent></Card>}
      <section className="grid gap-3 md:grid-cols-2">{query.data.data.payslips.map((slip) => <Card key={slip.id} className="overflow-hidden"><CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0 p-4"><div><CardTitle className="text-base">{monthLabel(slip.period)}</CardTitle><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5"/>{slip.payPeriodStart ? new Date(slip.payPeriodStart).toLocaleDateString() : ""}{slip.payPeriodEnd ? ` – ${new Date(slip.payPeriodEnd).toLocaleDateString()}` : ""}</p></div><span className={`rounded-full px-2 py-1 text-xs font-medium ${slip.payment.status === "paid" ? "bg-emerald-500/10 text-emerald-600" : "bg-amber-500/10 text-amber-600"}`}>{slip.payment.status === "paid" ? "Paid" : "Finalized"}</span></CardHeader><CardContent className="space-y-3 px-4 pb-4"><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded-lg bg-muted/50 p-3"><span className="text-xs text-muted-foreground">Gross pay</span><b className="mt-1 block">{money(slip.earnings.grossSalary)}</b></div><div className="rounded-lg bg-emerald-500/10 p-3"><span className="text-xs text-muted-foreground">Net pay</span><b className="mt-1 block text-emerald-600">{money(slip.netPay)}</b></div></div><details className="group rounded-lg border p-3"><summary className="cursor-pointer list-none text-sm font-medium">Payroll breakdown <span className="float-right text-muted-foreground group-open:rotate-180">⌄</span></summary><div className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><span>PAYE</span><span>{money(slip.deductions.paye)}</span></div><div className="flex justify-between"><span>RSSB employee pension</span><span>{money(slip.deductions.rssbEmployeePension)}</span></div><div className="flex justify-between"><span>RSSB maternity</span><span>{money(slip.deductions.rssbEmployeeMaternity)}</span></div><div className="flex justify-between"><span>Other deductions</span><span>{money(slip.deductions.totalDeductions - slip.deductions.paye - slip.deductions.rssbEmployeePension - slip.deductions.rssbEmployeeMaternity)}</span></div><div className="flex justify-between border-t pt-2"><span>Employer contributions</span><span>{money(Object.values(slip.employerContributions).reduce((sum, value) => sum + Number(value || 0), 0))}</span></div></div></details><div className="flex items-center justify-between gap-2"><p className="flex items-center gap-1 text-xs text-muted-foreground"><Banknote className="h-3.5 w-3.5"/>{slip.payment.paymentDate ? `Paid ${new Date(slip.payment.paymentDate).toLocaleDateString()}` : "Payment date not recorded"}</p><Button size="sm" variant="outline" onClick={() => download(slip.id, query.data!.data.employee.employeeId)}><Download className="mr-2 h-4 w-4"/>Payslip</Button></div></CardContent></Card>)}</section>
    </>}
  </main></Layout>;
}
