import { useEffect, useState } from "react";
import { projectsApi, type Project } from "@/lib/api";
import { Button } from "@/app/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/card";
import { toast } from "sonner";
import { Download, Printer, RefreshCw } from "lucide-react";
import { useFormatCurrency } from "@/lib/currencyUtils";

const csvCell = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;

export default function ProjectReportsPanel({ project }: { project: Project }) {
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const formatCurrency = useFormatCurrency();
  const load = async () => { setLoading(true); try { setReport((await projectsApi.getReport(project._id)).data); } catch (error: any) { toast.error(error?.message || "Could not load project reports"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [project._id]);
  const download = () => {
    if (!report) return;
    const rows: unknown[][] = [["Project report", project.project_code, project.name], ["Generated", report.generated_at], [], ["Tasks"], ["WBS", "Task", "Status", "Progress %", "Estimated hours", "Actual hours", "Due date"], ...report.tasks.map((task: any) => [task.wbs_code, task.name, task.status, task.progress_percent, task.estimated_hours, task.timesheet_hours || task.actual_hours, task.end_date]), [], ["Milestones"], ["Milestone", "Status", "Priority", "Progress %", "Due date"], ...report.milestones.map((item: any) => [item.name, item.status, item.priority, item.progress_percent, item.due_date]), [], ["Budget lines"], ["Project/WBS", "Account", "Year", "Month", "Budgeted", "Actual", "Encumbered"], ...report.budget_lines.map((line: any) => [line.project_id?.wbs_code || line.wbs_code, line.account_id?.name || line.account_id, line.period_year, line.period_month, line.budgeted_amount, line.actual_amount, line.encumbered_amount]), [], ["Material requisitions"], ["Requisition", "Status", "Product", "Task", "Warehouse", "Planned qty", "Issued qty", "Returned qty", "Unit cost"], ...report.material_requisitions.flatMap((req: any) => req.lines.map((line: any) => [req.requisitionNo, req.status, line.product?.name || line.productId, line.task?.name || "", line.warehouse?.name || "", line.plannedQuantity, line.issuedQuantity, line.returnedQuantity, line.unitCost])), [], ["Risk, issue and change register"], ["Reference", "Type", "Title", "Status", "Priority", "Owner", "Due date", "Cost impact", "Schedule impact days", "Mitigation", "Decision"], ...report.controls.map((item: any) => [item.referenceNo, item.type, item.title, item.status, item.priority, item.ownerName, item.dueDate, item.impactCost, item.impactDays, item.mitigation, item.decision]), [], ["Risks"], ["Type", "Severity", "Title", "Reference", "Due date", "Amount"], ...report.risks.map((risk: any) => [risk.type, risk.severity, risk.title, risk.reference, risk.due_date, risk.amount])];
    const blob = new Blob([rows.map((row) => (row as unknown[]).map(csvCell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${project.project_code}-project-report.csv`; anchor.click(); URL.revokeObjectURL(url);
  };
  const summary = report?.executive_summary;
  const countStatus = (statuses: Record<string, number> = {}) => Object.entries(statuses).map(([key, value]) => `${key}: ${value}`).join(" · ") || "No records";
  if (loading && !report) return <p className="py-10 text-center text-sm text-muted-foreground">Loading project reports…</p>;
  if (!report) return <div className="py-8 text-center"><p className="mb-3 text-sm text-muted-foreground">Project report is unavailable.</p><Button variant="outline" onClick={() => void load()}>Retry</Button></div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Project reporting suite</h3><p className="text-sm text-muted-foreground">Generated {new Date(report.generated_at).toLocaleString()}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button><Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="mr-2 h-4 w-4" />Print</Button><Button size="sm" onClick={download}><Download className="mr-2 h-4 w-4" />Export CSV</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      ["Progress", `${summary.progress_percent.toFixed(1)}%`, `${summary.task_count} tasks · ${summary.overdue_task_count} overdue`],
      ["Schedule", `${summary.actual_hours.toFixed(1)} / ${summary.planned_hours.toFixed(1)} hrs`, `${summary.overdue_milestone_count} overdue milestones`],
      ["Budget forecast", formatCurrency(summary.financial.forecast_budget_cost, summary.financial.currency_code), `${formatCurrency(summary.financial.budget_variance_at_completion, summary.financial.currency_code)} variance`],
      ["Materials", formatCurrency(summary.materials.issued_cost, summary.materials.currency_code), `${formatCurrency(summary.materials.open_commitment, summary.materials.currency_code)} commitment`],
    ].map(([label, value, detail]) => <Card key={label}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>)}</div>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Work status</CardTitle></CardHeader><CardContent><p className="text-sm">Tasks: {countStatus(summary.task_status_counts)}</p><p className="mt-2 text-sm">Milestones: {countStatus(summary.milestone_status_counts)}</p><p className="mt-2 text-sm">Approved labor: {summary.labor.total_hours.toFixed(2)} hrs across {summary.labor.total_entries} entries</p>{summary.labor.by_currency.map((row: any) => <p key={row.currency_code} className="mt-1 text-sm text-muted-foreground">{row.currency_code} {Number(row.amount).toLocaleString()} actual labor</p>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Risks & closure readiness</CardTitle></CardHeader><CardContent><p className="mb-2 text-sm">{report.risks.length ? `${report.risks.length} item(s) need attention` : "No schedule or budget risks detected"}</p><p className="mb-3 text-sm text-muted-foreground">Closure: {report.closure_checklist.can_close ? "Ready" : `${report.closure_checklist.blockers.length} item(s) remain`}</p>{report.risks.slice(0, 6).map((risk: any, index: number) => <div key={`${risk.type}-${index}`} className="flex justify-between gap-3 border-t py-2 text-sm"><span>{risk.title}</span><span className="text-muted-foreground">{risk.severity}</span></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">Task register ({report.tasks.length})</CardTitle></CardHeader><CardContent><div className="max-h-80 overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">WBS</th><th className="p-2">Task</th><th className="p-2">Status</th><th className="p-2">Progress</th><th className="p-2">Hours</th><th className="p-2">Due</th></tr></thead><tbody>{report.tasks.map((task: any) => <tr key={task._id} className="border-b"><td className="p-2">{task.wbs_code}</td><td className="p-2">{task.name}</td><td className="p-2">{task.status}</td><td className="p-2">{Number(task.progress_percent || 0).toFixed(0)}%</td><td className="p-2">{Number(task.timesheet_hours || task.actual_hours || 0).toFixed(1)} / {Number(task.estimated_hours || 0).toFixed(1)}</td><td className="p-2">{task.end_date ? new Date(task.end_date).toLocaleDateString() : "—"}</td></tr>)}</tbody></table></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Milestone register ({report.milestones.length})</CardTitle></CardHeader><CardContent><div className="max-h-64 overflow-auto">{report.milestones.length ? report.milestones.map((item: any) => <div key={item.id} className="flex flex-wrap justify-between gap-2 border-b py-2 text-sm"><span>{item.name}</span><span className="text-muted-foreground">{item.status} · {item.priority} · {item.due_date ? new Date(item.due_date).toLocaleDateString() : "No due date"}</span></div>) : <p className="text-sm text-muted-foreground">No milestones recorded.</p>}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Budget vs actual ({report.budget_lines.length} lines)</CardTitle></CardHeader><CardContent><div className="max-h-72 overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">WBS / Account</th><th className="p-2">Period</th><th className="p-2 text-right">Budget</th><th className="p-2 text-right">Actual</th><th className="p-2 text-right">Committed</th></tr></thead><tbody>{report.budget_lines.map((line: any) => <tr key={line._id} className="border-b"><td className="p-2">{line.project_id?.wbs_code || line.wbs_code || "—"} · {line.account_id?.name || "Account"}</td><td className="p-2">{line.period_month}/{line.period_year}</td><td className="p-2 text-right">{formatCurrency(Number(line.budgeted_amount || 0))}</td><td className="p-2 text-right">{formatCurrency(Number(line.actual_amount || 0))}</td><td className="p-2 text-right">{formatCurrency(Number(line.encumbered_amount || 0))}</td></tr>)}</tbody></table>{!report.budget_lines.length && <p className="py-4 text-sm text-muted-foreground">No approved project budget lines.</p>}</div></CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Labor cost by task</CardTitle></CardHeader><CardContent><div className="max-h-72 overflow-auto">{summary.labor.by_task.map((row: any) => <div key={row.task_id} className="flex justify-between gap-3 border-b py-2 text-sm"><span className="truncate">{row.wbs_code} · {row.task_name} ({Number(row.hours).toFixed(1)} hrs)</span><span>{Object.entries(row.cost_by_currency).map(([code, amount]) => `${code} ${Number(amount).toLocaleString()}`).join(" · ")}</span></div>)}{!summary.labor.by_task.length && <p className="text-sm text-muted-foreground">No approved timesheet labor.</p>}</div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Materials by requisition</CardTitle></CardHeader><CardContent><div className="max-h-72 overflow-auto">{report.material_requisitions.flatMap((req: any) => req.lines.map((line: any) => <div key={line.id} className="flex justify-between gap-3 border-b py-2 text-sm"><span>{req.requisitionNo} · {line.product?.name || line.productId} · {line.task?.wbsCode || "Project"}</span><span>{Number(line.issuedQuantity)} issued / {Number(line.plannedQuantity)} planned</span></div>))}{!report.material_requisitions.length && <p className="text-sm text-muted-foreground">No material requisitions.</p>}</div></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">Risk, issue & change register ({report.controls.length})</CardTitle></CardHeader><CardContent><div className="max-h-80 overflow-auto">{report.controls.map((item: any) => <div key={item.id} className="flex flex-wrap justify-between gap-3 border-b py-2 text-sm"><span><span className="mr-2 font-mono text-xs text-muted-foreground">{item.referenceNo}</span>{item.title}</span><span className="text-muted-foreground">{item.type} · {item.status} · {item.priority} · {Number(item.impactDays).toFixed(1)}d</span></div>)}{!report.controls.length && <p className="text-sm text-muted-foreground">No risk, issue, or change records.</p>}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Recent project activity ({report.activity.length}) · Documents {report.documents.length}</CardTitle></CardHeader><CardContent><div className="max-h-60 overflow-auto">{report.activity.slice(0, 20).map((item: any) => <div key={item.id} className="flex flex-wrap justify-between gap-2 border-b py-2 text-sm"><span>{item.message}</span><span className="text-muted-foreground">{item.actorName} · {new Date(item.createdAt).toLocaleDateString()}</span></div>)}</div></CardContent></Card>
    <p className="text-xs text-muted-foreground">Financial report uses approved linked budget lines, the project budget forecast, approved task labor, and project material issue/return records. Contract value is a planned revenue measure; invoiced revenue is not linked to projects in the current data model.</p>
  </div>;
}
